### ISSUE TITLE
Support creating pulse on 1 line

### ISSUE THREAD

**Issue by sbunciak** [px3/camel-gpio#6]

**Comment by pmacik** [comment]
To send a pulse of a particular length use a comination of 'value' and 'pulseInMicroseconds" properites.

Example:
To send a HIGH pulse 42 microseconds long to pin PB10, use following camel route configuration:

```xml
<route id="...">
   <from uri="..." />
   <to uri="gpio://pb10?value=HIGH&amp;pulseInMicroseconds=42" />
</route>
```
